openapi: "3.0.03"
info:
  title: Zips REST API"
  decsription: "My first API"
  version: "v1.0"

servers:
    -url: http://localhost:3020
    description: "dev Server"

paths:
    /api/states:
      get:
          description: get a list of all /api/states
          operationId: getStates
          responses:
              200:
                  description: Default reprezentation
                  content:
                      applictation/json:
  