openapi: "3.0.3"
info:
  title: "Zips REST API"
  description: "My first API"
  version: "v1.0"

servers:
    - url: http://localhost:3040
      description: "dev Server"

components:
    schemas:
        states:
             type: string
             enum: [ "MA", "RI", "NH", "ME", "VT", "CT", "NY", "NJ", "PA", "DE", "DC", "MD", "VA", "WV", "NC", "SC","GA", "FL", "AL", "TN", "MS", "KY", "OH", "IN","MI", "IA", "WI", "MN", "SD", "ND", "MT", "IL", "MO", "KS", "NE", "LA", "AR", "OK", "TX", "CO","WY", "ID", "UT", "AZ", "NM", "NV", "CA", "HI","OR", "WA", "AK" ]
             description: state
        city-form:
            type: object
            properties:
                city:
                    type: string
                    description: city name
                loc:
                    type: string
                    description: location in string
                lat:
                    type: number
                    description: location
                pop:
                    type: number
                    minimum: 10
                    description: population
                state:
                    type: string
                    enum: [ "MA", "RI", "NH", "ME", "VT", "CT", "NY", "NJ", "PA", "DE", "DC", "MD", "VA", "WV", "NC", "SC","GA", "FL", "AL", "TN", "MS", "KY", "OH", "IN","MI", "IA", "WI", "MN", "SD", "ND", "MT", "IL", "MO", "KS", "NE", "LA", "AR", "OK", "TX", "CO","WY", "ID", "UT", "AZ", "NM", "NV", "CA", "HI","OR", "WA", "AK" ]
                    description: state
            required: ["city", "pop", "lat", "loc" ,"state"]

        city:
            type: object
            properties:
                _id:
                    type: string
                    description: _id
                city:
                    type: string
                    description: city name
                loc:
                    type: array
                    items:
                        type: number
                    maxItems: 2
                    minItems: 2
                    description: location
                pop:
                    type: number
                    minimum: 10
                    description: population
                state:
                    type: string
                    enum: [ "MA", "RI", "NH", "ME", "VT", "CT", "NY", "NJ", "PA", "DE", "DC", "MD", "VA", "WV", "NC", "SC","GA", "FL", "AL", "TN", "MS", "KY", "OH", "IN","MI", "IA", "WI", "MN", "SD", "ND", "MT", "IL", "MO", "KS", "NE", "LA", "AR", "OK", "TX", "CO","WY", "ID", "UT", "AZ", "NM", "NV", "CA", "HI","OR", "WA", "AK" ]
                    description: state


paths:
    /api/city:
      post:
        description: add new city
        operationId: addCity
        requestBody:
            required: true
            content:
                application/x-www-form-urlencoded:
                    schema: 
                        $ref: "#/components/schemas/city-form"
                application/json:
                    schema:
                        $ref: "#/components/schemas/city"
        responses:
            201:
                description: Success
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                message:
                                    type: string
                            required: ["message"]
                            
                        



    /api/states:
      get:
          description: get a list of all /api/states
          operationId: getStates
          responses:
              200:
                  description: Default reprezentation
                  content:
                      application/json:
                        schema:
                            type: array
                            items: 
                                type: string
    /api/state/{stateId}:
      get:
          description: get a city in state
          operationId: getCitiesFromState
          parameters:
            - name: stateId
              in: path
              required: true
              schema:
                $ref: "#/components/schemas/states" 
            - name: offset
              in: query
              schema:
                type: number
                minimum: 0
            - name: limit
              in: query
              schema:
                type: number
                minimum: 1

          responses:
              200:
                  description: Success
                  content:
                      application/json:
                        schema:
                            type: array
                            items:
                                $ref: "#/components/schemas/city"
                    