# coding: utf-8

"""
    Zips REST API

    My first API  # noqa: E501

    The version of the OpenAPI document: v1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.states import States  # noqa: E501
from openapi_client.rest import ApiException

class TestStates(unittest.TestCase):
    """States unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test States
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.states.States()  # noqa: E501
        if include_optional :
            return States(
            )
        else :
            return States(
        )

    def testStates(self):
        """Test States"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
