# coding: utf-8

# flake8: noqa
"""
    Zips REST API

    My first API  # noqa: E501

    The version of the OpenAPI document: v1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.city import City
from openapi_client.models.states import States
